INFO 2025-06-24 16:54:47,891 autoreload Watching for file changes with StatReloader
INFO 2025-06-24 16:54:57,581 basehttp "GET /documents/ HTTP/1.1" 200 17375
INFO 2025-06-24 16:55:01,583 basehttp "POST /documents/1/process/ HTTP/1.1" 200 123
INFO 2025-06-24 16:55:16,326 autoreload Watching for file changes with StatReloader
INFO 2025-06-24 16:56:05,467 autoreload /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_project/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_project/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /documents/ HTTP/1.1" 200 17375
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_project/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "POST /documents/1/process/ HTTP/1.1" 200 191
INFO "GET /documents/ HTTP/1.1" 200 17717
ERROR Internal Server Error: /documents/1/results/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 274, in pdf_results
    return render(request, 'manifest_app/pdf_results.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 678, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse some characters: manifest_entries.values|:'vessel'||length
ERROR "GET /documents/1/results/ HTTP/1.1" 500 255067
INFO "GET /donnees/ HTTP/1.1" 200 14613
INFO "GET /donnees/ HTTP/1.1" 200 14613
INFO "GET /documents/ HTTP/1.1" 200 17717
INFO "GET /documents/upload/ HTTP/1.1" 200 15889
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 20542
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/services/ai_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /documents/ HTTP/1.1" 200 20191
INFO "POST /documents/2/process/ HTTP/1.1" 200 191
INFO "GET /documents/ HTTP/1.1" 200 20533
ERROR Internal Server Error: /documents/2/results/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 274, in pdf_results
    return render(request, 'manifest_app/pdf_results.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 678, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse some characters: manifest_entries.values|:'vessel'||length
ERROR "GET /documents/2/results/ HTTP/1.1" 500 253895
INFO "GET /donnees/ HTTP/1.1" 200 17325
INFO "GET /utilisateurs/ HTTP/1.1" 200 15353
INFO "GET /documents/ HTTP/1.1" 200 20533
ERROR Internal Server Error: /documents/2/results/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 274, in pdf_results
    return render(request, 'manifest_app/pdf_results.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 678, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse some characters: manifest_entries.values|:'vessel'||length
ERROR "GET /documents/2/results/ HTTP/1.1" 500 253895
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /documents/2/results/ HTTP/1.1" 200 20961
INFO "GET /donnees/ HTTP/1.1" 200 17325
INFO "GET /utilisateurs/ HTTP/1.1" 200 15353
INFO "GET /documents/ HTTP/1.1" 200 20533
INFO "GET /statistiques/ HTTP/1.1" 200 20282
INFO "GET / HTTP/1.1" 200 19086
INFO "GET / HTTP/1.1" 200 19086
ERROR Internal Server Error: /vessels/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 134, in vessels
    return render(request, 'manifest_app/vessels.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: manifest_app/vessels.html
ERROR "GET /vessels/ HTTP/1.1" 500 91426
INFO "GET /donnees/ HTTP/1.1" 200 17325
INFO "GET /documents/ HTTP/1.1" 200 20533
INFO "GET /statistiques/ HTTP/1.1" 200 20282
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /statistiques/ HTTP/1.1" 200 20282
INFO "GET / HTTP/1.1" 200 33875
INFO "GET / HTTP/1.1" 200 32910
INFO "GET /statistiques/ HTTP/1.1" 200 20282
INFO "GET /donnees/ HTTP/1.1" 200 17325
INFO "GET /utilisateurs/ HTTP/1.1" 200 15353
ERROR Internal Server Error: /vessels/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 221, in vessels
    return render(request, 'manifest_app/vessels.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: manifest_app/vessels.html
ERROR "GET /vessels/ HTTP/1.1" 500 91439
ERROR Internal Server Error: /consignes/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 245, in consignes
    return render(request, 'manifest_app/consignes.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: manifest_app/consignes.html
ERROR "GET /consignes/ HTTP/1.1" 500 91462
INFO "GET / HTTP/1.1" 200 33875
INFO "GET /donnees/ HTTP/1.1" 200 17325
INFO "GET /donnees/ HTTP/1.1" 200 13660
INFO "GET /documents/ HTTP/1.1" 200 16868
INFO "GET / HTTP/1.1" 200 30210
INFO "GET /statistiques/ HTTP/1.1" 200 16617
INFO "GET /utilisateurs/ HTTP/1.1" 200 11688
INFO "GET /statistiques/ HTTP/1.1" 200 16617
INFO "GET / HTTP/1.1" 200 30210
INFO "GET / HTTP/1.1" 200 26545
INFO "GET / HTTP/1.1" 200 30210
INFO "GET / HTTP/1.1" 200 30210
INFO "GET / HTTP/1.1" 200 30210
INFO "GET /statistiques/ HTTP/1.1" 200 16617
INFO "GET /documents/ HTTP/1.1" 200 16868
INFO "GET /donnees/ HTTP/1.1" 200 13660
INFO "GET /documents/ HTTP/1.1" 200 16868
INFO "GET /documents/1/results/ HTTP/1.1" 200 11164
INFO "GET /documents/ HTTP/1.1" 200 16868
INFO "GET /documents/upload/ HTTP/1.1" 200 12234
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 19691
INFO "POST /documents/3/process/ HTTP/1.1" 200 191
INFO "GET /documents/ HTTP/1.1" 200 19683
INFO "GET /documents/3/results/ HTTP/1.1" 200 29926
INFO "GET /documents/ HTTP/1.1" 200 19683
INFO "GET /utilisateurs/ HTTP/1.1" 200 11688
INFO "GET /donnees/ HTTP/1.1" 200 28135
INFO "GET /documents/ HTTP/1.1" 200 19683
INFO "GET /statistiques/ HTTP/1.1" 200 22509
INFO "GET / HTTP/1.1" 200 42137
INFO "GET /statistiques/ HTTP/1.1" 200 22509
INFO "GET /documents/ HTTP/1.1" 200 19683
INFO "GET /donnees/ HTTP/1.1" 200 28135
INFO "GET /utilisateurs/ HTTP/1.1" 200 11688
INFO "GET /documents/ HTTP/1.1" 200 19683
INFO "GET /statistiques/ HTTP/1.1" 200 22509
INFO "GET / HTTP/1.1" 200 42137
INFO "GET /statistiques/ HTTP/1.1" 200 22509
INFO "GET /statistiques/ HTTP/1.1" 200 27158
INFO "GET / HTTP/1.1" 200 46786
INFO "GET / HTTP/1.1" 200 40482
INFO "GET / HTTP/1.1" 200 41329
INFO "GET / HTTP/1.1" 200 41329
INFO "GET /donnees/ HTTP/1.1" 200 33631
INFO "GET /utilisateurs/ HTTP/1.1" 200 17184
INFO "GET /donnees/ HTTP/1.1" 200 33631
INFO "GET /documents/ HTTP/1.1" 200 25179
INFO "GET /donnees/ HTTP/1.1" 200 33631
INFO "GET /utilisateurs/ HTTP/1.1" 200 17184
INFO "GET /documents/ HTTP/1.1" 200 25179
INFO "GET /statistiques/ HTTP/1.1" 200 28005
INFO "GET / HTTP/1.1" 200 41329
WARNING Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 6478
INFO "GET / HTTP/1.1" 200 41308
INFO "GET / HTTP/1.1" 200 41320
INFO "GET /statistiques/ HTTP/1.1" 200 27996
INFO "GET /documents/ HTTP/1.1" 200 25170
INFO "GET /donnees/ HTTP/1.1" 200 33622
INFO "GET /utilisateurs/ HTTP/1.1" 200 17175
INFO "GET /utilisateurs/ HTTP/1.1" 200 14035
INFO "GET /utilisateurs/ HTTP/1.1" 200 14107
INFO "GET /utilisateurs/ HTTP/1.1" 200 14103
INFO "GET /utilisateurs/ HTTP/1.1" 200 14105
INFO "GET /utilisateurs/ HTTP/1.1" 200 14105
INFO "GET /utilisateurs/ HTTP/1.1" 200 14105
INFO "GET /utilisateurs/ HTTP/1.1" 200 14105
INFO "GET /utilisateurs/ HTTP/1.1" 200 14105
INFO "GET / HTTP/1.1" 200 38250
INFO "GET /statistiques/ HTTP/1.1" 200 24926
INFO "GET /documents/ HTTP/1.1" 200 22100
INFO "GET /statistiques/ HTTP/1.1" 200 24926
INFO "GET /donnees/ HTTP/1.1" 200 30552
INFO "GET /utilisateurs/ HTTP/1.1" 200 14105
INFO "GET /donnees/ HTTP/1.1" 200 30552
INFO "GET / HTTP/1.1" 200 38250
INFO "GET /utilisateurs/ HTTP/1.1" 200 14105
INFO "GET /utilisateurs/ HTTP/1.1" 200 14105
INFO "GET /donnees/ HTTP/1.1" 200 30552
INFO "GET /documents/ HTTP/1.1" 200 22100
INFO "GET / HTTP/1.1" 200 38250
INFO "GET /statistiques/ HTTP/1.1" 200 24926
INFO "GET /statistiques/ HTTP/1.1" 200 24884
INFO "GET / HTTP/1.1" 200 38208
ERROR Internal Server Error: /vessels/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 221, in vessels
    return render(request, 'manifest_app/vessels.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: manifest_app/vessels.html
ERROR "GET /vessels/ HTTP/1.1" 500 91577
INFO "GET /donnees/ HTTP/1.1" 200 30510
INFO "GET /documents/ HTTP/1.1" 200 22058
INFO "GET /statistiques/ HTTP/1.1" 200 24884
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO "GET / HTTP/1.1" 302 0
INFO "GET /login/?next=/ HTTP/1.1" 200 9433
INFO "POST /login/?next=/ HTTP/1.1" 302 0
INFO "GET / HTTP/1.1" 200 42328
INFO "GET /chatbot/advanced/ HTTP/1.1" 200 30948
INFO "POST /api/chatbot/ HTTP/1.1" 200 56
INFO "POST /api/chatbot/ HTTP/1.1" 200 56
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "POST /api/chatbot/ HTTP/1.1" 200 64
INFO "POST /api/chatbot/ HTTP/1.1" 200 64
INFO "POST /api/chatbot/ HTTP/1.1" 200 64
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /chatbot/advanced/ HTTP/1.1" 200 30948
INFO "POST /api/chatbot/ HTTP/1.1" 200 64
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "POST /api/chatbot/ HTTP/1.1" 200 64
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "POST /api/chatbot/ HTTP/1.1" 200 64
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "POST /api/chatbot/ HTTP/1.1" 200 434
INFO "POST /api/chatbot/ HTTP/1.1" 200 64
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "POST /api/chatbot/ HTTP/1.1" 200 613
INFO "POST /api/chatbot/ HTTP/1.1" 200 906
ERROR Internal Server Error: /vessels/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 218, in vessels
    return render(request, 'manifest_app/vessels.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: manifest_app/vessels.html
ERROR "GET /vessels/ HTTP/1.1" 500 94554
ERROR Internal Server Error: /consignes/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 242, in consignes
    return render(request, 'manifest_app/consignes.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: manifest_app/consignes.html
ERROR "GET /consignes/ HTTP/1.1" 500 94426
INFO "GET / HTTP/1.1" 200 42328
INFO "GET / HTTP/1.1" 200 43173
INFO "GET /chatbot/advanced/ HTTP/1.1" 200 38280
INFO "GET /chatbot/advanced/ HTTP/1.1" 200 37677
INFO "GET / HTTP/1.1" 200 42570
INFO "GET / HTTP/1.1" 200 40748
INFO "GET /utilisateurs/ HTTP/1.1" 200 16603
INFO "GET /donnees/ HTTP/1.1" 200 33050
INFO "GET /documents/ HTTP/1.1" 200 24598
INFO "GET /statistiques/ HTTP/1.1" 200 27424
INFO "GET /chatbot/advanced/ HTTP/1.1" 200 35855
INFO "GET / HTTP/1.1" 200 40748
INFO Watching for file changes with StatReloader
INFO "GET /admin/ HTTP/1.1" 200 10154
INFO "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 7438
INFO "GET / HTTP/1.1" 200 40889
INFO Watching for file changes with StatReloader
INFO "GET / HTTP/1.1" 200 40889
INFO "GET / HTTP/1.1" 200 40889
INFO "GET /statistiques/ HTTP/1.1" 200 27630
INFO "GET / HTTP/1.1" 200 40889
INFO "GET / HTTP/1.1" 200 40882
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
WARNING Not Found: /images/logo-gnosis.png
WARNING "GET /images/logo-gnosis.png HTTP/1.1" 404 7471
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 200 0
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 200 0
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 7438
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 200 0
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 7438
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 200 0
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 7438
INFO "GET / HTTP/1.1" 200 40881
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
INFO "GET / HTTP/1.1" 200 40881
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 200 0
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 7438
INFO "GET / HTTP/1.1" 200 40881
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 200 364003
INFO "GET / HTTP/1.1" 200 40881
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
INFO "GET / HTTP/1.1" 200 40880
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
INFO "GET /utilisateurs/ HTTP/1.1" 200 16800
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
INFO "GET /logout/ HTTP/1.1" 302 0
INFO "GET /login/ HTTP/1.1" 200 5876
INFO "POST /login/ HTTP/1.1" 302 0
INFO "GET / HTTP/1.1" 200 40880
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/forms.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /logout/ HTTP/1.1" 302 0
INFO "GET /login/ HTTP/1.1" 200 5876
INFO "POST /login/ HTTP/1.1" 302 0
INFO "GET / HTTP/1.1" 200 40880
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
INFO "GET /utilisateurs/ HTTP/1.1" 200 16815
INFO "GET /utilisateurs/create/ HTTP/1.1" 200 20558
INFO "POST /utilisateurs/create/ HTTP/1.1" 200 21004
INFO "POST /utilisateurs/create/ HTTP/1.1" 200 20846
INFO "POST /utilisateurs/create/ HTTP/1.1" 302 0
INFO "GET /utilisateurs/ HTTP/1.1" 200 19852
INFO Watching for file changes with StatReloader
INFO "GET /utilisateurs/ HTTP/1.1" 200 18829
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
INFO "GET /utilisateurs/2/delete/ HTTP/1.1" 200 16830
INFO "POST /utilisateurs/2/delete/ HTTP/1.1" 302 0
INFO "GET /utilisateurs/ HTTP/1.1" 200 17683
INFO "GET /logout/ HTTP/1.1" 302 0
INFO "GET /login/ HTTP/1.1" 200 14945
WARNING "GET /static/images/logo-gnosis.png HTTP/1.1" 404 1880
INFO "GET /login/ HTTP/1.1" 200 14944
INFO "GET /login/ HTTP/1.1" 200 14946
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 200 99816
INFO "GET /login/ HTTP/1.1" 200 14946
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 200 67739
INFO "GET /login/ HTTP/1.1" 200 15024
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 304 0
INFO "POST /login/ HTTP/1.1" 302 0
INFO "GET / HTTP/1.1" 200 40958
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
INFO "GET /logout/ HTTP/1.1" 302 0
INFO "GET /login/ HTTP/1.1" 200 15024
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 304 0
INFO "POST /login/ HTTP/1.1" 302 0
INFO "GET / HTTP/1.1" 200 40958
ERROR Internal Server Error: /vessels/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 264, in vessels
    return render(request, 'manifest_app/vessels.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: manifest_app/vessels.html
ERROR "GET /vessels/ HTTP/1.1" 500 95469
ERROR Internal Server Error: /vessels/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 264, in vessels
    return render(request, 'manifest_app/vessels.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: manifest_app/vessels.html
ERROR "GET /vessels/ HTTP/1.1" 500 95469
INFO "GET /donnees/ HTTP/1.1" 200 33325
INFO "GET /documents/ HTTP/1.1" 200 24873
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /documents/ HTTP/1.1" 200 25170
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 304 0
INFO "GET /documents/3/view/ HTTP/1.1" 200 1115460
INFO "GET / HTTP/1.1" 200 40958
ERROR Internal Server Error: /vessels/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 329, in vessels
    return render(request, 'manifest_app/vessels.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 701, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 611, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
ERROR "GET /vessels/ HTTP/1.1" 500 318821
INFO "GET /vessels/ HTTP/1.1" 200 36355
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
ERROR Internal Server Error: /vessels/3/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py", line 344, in vessel_detail
    avg_weight=Avg('poids'),
               ^^^
NameError: name 'Avg' is not defined
ERROR "GET /vessels/3/ HTTP/1.1" 500 79656
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /vessels/3/ HTTP/1.1" 200 19807
INFO "GET /vessels/2/ HTTP/1.1" 200 19802
INFO "GET /vessels/ HTTP/1.1" 200 36355
INFO "GET /vessels/1/ HTTP/1.1" 200 19826
INFO "GET /vessels/1/ HTTP/1.1" 200 19826
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 304 0
INFO "GET /vessels/ HTTP/1.1" 200 34015
INFO "GET / HTTP/1.1" 200 40958
INFO "GET /chatbot/advanced/ HTTP/1.1" 200 36130
INFO "POST /api/chatbot/ HTTP/1.1" 200 700
INFO /home/akemi/Bureau/Gnosis/last/django-manifest-app/manifest_project/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 8573
INFO Watching for file changes with StatReloader
INFO "GET /admin/ HTTP/1.1" 200 10154
INFO "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 8573
INFO "GET /admin/manifest_app/manifestentry/ HTTP/1.1" 200 19216
INFO "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO "GET /admin/manifest_app/manifestentry/11/change/ HTTP/1.1" 200 19804
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
INFO "GET /admin/manifest_app/manifestentry/ HTTP/1.1" 200 19216
INFO "GET /admin/ HTTP/1.1" 200 10154
INFO "GET / HTTP/1.1" 200 40958
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 304 0
INFO "GET /documents/ HTTP/1.1" 200 25170
INFO "GET /donnees/ HTTP/1.1" 200 33325
INFO Watching for file changes with StatReloader
INFO "GET /documents/4/process/ HTTP/1.1" 302 0
INFO "GET /login/?next=/documents/4/process/ HTTP/1.1" 200 15024
INFO "POST /login/?next=/documents/4/process/ HTTP/1.1" 302 0
INFO "GET / HTTP/1.1" 200 40958
INFO "GET /documents/ HTTP/1.1" 200 25170
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 28698
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/models.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/models.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET / HTTP/1.1" 302 0
INFO "GET /login/?next=/ HTTP/1.1" 200 15024
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 304 0
INFO "GET / HTTP/1.1" 302 0
INFO "GET /login/?next=/ HTTP/1.1" 200 15024
INFO "GET /login/?next=/ HTTP/1.1" 200 15024
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 200 67739
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 200 67739
INFO "POST /login/?next=/ HTTP/1.1" 302 0
INFO "GET / HTTP/1.1" 200 42238
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 304 0
INFO "GET / HTTP/1.1" 200 42238
INFO "GET /chatbot/advanced/ HTTP/1.1" 200 38378
INFO "POST /api/chatbot/ HTTP/1.1" 200 431
ERROR Internal Server Error: /statistiques/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/v3/manifest_app/views.py", line 211, in statistiques
    return render(request, 'manifest_app/statistiques.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1379, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'voyage'. Choices are: pdf_document, vessel, container, shipper, consigne
ERROR "GET /statistiques/ HTTP/1.1" 500 222353
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 8573
INFO "GET /documents/ HTTP/1.1" 200 27755
INFO "GET /documents/ HTTP/1.1" 200 27755
INFO Watching for file changes with StatReloader
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 31273
INFO "GET /documents/5/view/ HTTP/1.1" 200 146871
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /donnees/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/v3/manifest_app/views.py", line 254, in donnees
    return render(request, 'manifest_app/donnees.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/paginator.py", line 191, in __len__
    return len(self.object_list)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1379, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'voyage'. Choices are: pdf_document, vessel, container, shipper, consigne
ERROR "GET /donnees/ HTTP/1.1" 500 225458
INFO "GET /documents/ HTTP/1.1" 200 30335
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 33863
INFO Watching for file changes with StatReloader
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 36441
INFO "POST /documents/7/process/ HTTP/1.1" 200 296
INFO "GET /documents/ HTTP/1.1" 200 35833
INFO "GET /admin/ HTTP/1.1" 200 10154
INFO "GET /admin/manifest_app/manifestentry/ HTTP/1.1" 200 19696
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/admin.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/admin.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/admin.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/admin.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/admin.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /admin/manifest_app/manifestentry/ HTTP/1.1" 200 20667
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/containercontent/ HTTP/1.1" 200 11729
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 11675
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 11675
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/containercontent/ HTTP/1.1" 200 11729
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/services/ai_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 39347
INFO "POST /documents/8/process/ HTTP/1.1" 200 296
INFO "GET /documents/ HTTP/1.1" 200 38742
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/services/ai_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/services/ai_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 41470
INFO "POST /documents/9/process/ HTTP/1.1" 200 296
INFO "GET /documents/ HTTP/1.1" 200 40855
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/services/ai_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 41466
INFO "POST /documents/10/process/ HTTP/1.1" 200 296
INFO "GET /documents/ HTTP/1.1" 200 40858
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/models.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 41471
INFO "GET /admin/manifest_app/containercontent/ HTTP/1.1" 200 11729
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 11675
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/shipper/ HTTP/1.1" 200 11661
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 11675
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/consigne/ HTTP/1.1" 200 11668
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "POST /documents/11/process/ HTTP/1.1" 200 296
INFO "GET /documents/ HTTP/1.1" 200 40862
INFO Watching for file changes with StatReloader
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 41798
INFO "POST /documents/12/process/ HTTP/1.1" 200 296
INFO "GET /documents/ HTTP/1.1" 200 41192
INFO "GET /admin/manifest_app/consigne/ HTTP/1.1" 200 13818
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/containercontent/ HTTP/1.1" 200 12780
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 15229
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/models.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO "POST /admin/manifest_app/container/ HTTP/1.1" 200 12232
INFO "GET /static/admin/js/cancel.js HTTP/1.1" 200 884
INFO "POST /admin/manifest_app/container/ HTTP/1.1" 302 0
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 11822
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO "GET /admin/manifest_app/consigne/ HTTP/1.1" 200 13818
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "POST /admin/manifest_app/consigne/ HTTP/1.1" 200 11593
INFO "POST /admin/manifest_app/consigne/ HTTP/1.1" 302 0
INFO "GET /admin/manifest_app/consigne/ HTTP/1.1" 200 11814
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 42134
INFO "POST /documents/13/process/ HTTP/1.1" 200 296
INFO "GET /documents/ HTTP/1.1" 200 41527
INFO "GET /admin/manifest_app/consigne/ HTTP/1.1" 200 13441
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/consigne/3/change/ HTTP/1.1" 200 13117
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/containercontent/ HTTP/1.1" 200 11729
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 11675
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/services/ai_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 42462
INFO "POST /documents/14/process/ HTTP/1.1" 200 296
INFO "GET /documents/ HTTP/1.1" 200 41856
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 11675
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 11675
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 11675
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/containercontent/ HTTP/1.1" 200 11729
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/consigne/ HTTP/1.1" 200 13441
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 11675
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /documents/upload/ HTTP/1.1" 200 17426
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 42464
INFO "POST /documents/15/process/ HTTP/1.1" 200 300
INFO "GET /documents/ HTTP/1.1" 200 41858
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 16998
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
ERROR Internal Server Error: /donnees/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/v3/manifest_app/views.py", line 254, in donnees
    return render(request, 'manifest_app/donnees.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/paginator.py", line 191, in __len__
    return len(self.object_list)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1379, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'voyage'. Choices are: pdf_document, vessel, container, shipper, consigne
ERROR "GET /donnees/ HTTP/1.1" 500 225321
WARNING Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 8684
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /donnees/ HTTP/1.1" 200 33803
INFO Watching for file changes with StatReloader
WARNING Not Found: /containers/
WARNING "GET /containers/ HTTP/1.1" 404 8573
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /containers/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'manifest_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/v3/manifest_app/views.py", line 282, in containers
    return render(request, 'manifest_app/containers.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'manifest_app' is not a registered namespace
ERROR "GET /containers/ HTTP/1.1" 500 244044
INFO "GET /containers/ HTTP/1.1" 200 49531
ERROR Internal Server Error: /containers/17/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'manifest_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/v3/manifest_app/views.py", line 305, in container_detail
    return render(request, 'manifest_app/container_detail.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'manifest_app' is not a registered namespace
ERROR "GET /containers/17/ HTTP/1.1" 500 191785
INFO "GET /containers/17/ HTTP/1.1" 200 25262
INFO "GET /containers/ HTTP/1.1" 200 49531
INFO "GET /containers/9/ HTTP/1.1" 200 25086
INFO "GET /containers/9/ HTTP/1.1" 200 25465
INFO "GET /containers/ HTTP/1.1" 200 49918
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /containers/ HTTP/1.1" 200 49918
INFO "GET /containers/?search=&type=&status=&vessel=2 HTTP/1.1" 200 22088
INFO "GET /containers/?search=&type=&status=&vessel=4 HTTP/1.1" 200 22088
INFO "GET /containers/?search=&type=&status=&vessel= HTTP/1.1" 200 49918
INFO "GET /containers/?search=&type=&status=&vessel=7 HTTP/1.1" 200 49926
INFO "GET /containers/?search=&type=&status=&vessel=7 HTTP/1.1" 200 59727
INFO "GET /containers/17/ HTTP/1.1" 200 28460
INFO "GET /containers/ HTTP/1.1" 200 61338
INFO "GET /containers/9/ HTTP/1.1" 200 28272
INFO "GET /containers/ HTTP/1.1" 200 61338
INFO "GET /containers/17/ HTTP/1.1" 200 28460
INFO "GET /containers/ HTTP/1.1" 200 61338
INFO "GET /containers/?search=LAs&type=&status=&vessel= HTTP/1.1" 200 61341
INFO "GET /containers/?search=ABDUL&type=&status=&vessel= HTTP/1.1" 200 40119
INFO "GET /containers/17/ HTTP/1.1" 200 28460
INFO "GET /containers/ HTTP/1.1" 200 61338
INFO "GET /donnees/ HTTP/1.1" 200 34182
INFO "GET /donnees/?page=4 HTTP/1.1" 200 22021
INFO "GET /containers/ HTTP/1.1" 200 61338
INFO "GET /chatbot/advanced/ HTTP/1.1" 200 40692
INFO "POST /api/chatbot/ HTTP/1.1" 200 582
INFO "POST /api/chatbot/ HTTP/1.1" 200 486
INFO "POST /api/chatbot/ HTTP/1.1" 200 826
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "POST /api/chatbot/ HTTP/1.1" 200 62
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "POST /api/chatbot/ HTTP/1.1" 200 62
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "POST /api/chatbot/ HTTP/1.1" 200 1972
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/services/chatbot_service.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /utilisateurs/ HTTP/1.1" 200 17179
INFO "GET / HTTP/1.1" 200 43849
INFO "GET /vessels/ HTTP/1.1" 200 39216
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /vessels/ HTTP/1.1" 200 39216
INFO "GET /vessels/ HTTP/1.1" 200 39216
INFO "GET /utilisateurs/ HTTP/1.1" 200 17179
INFO "GET /containers/ HTTP/1.1" 200 61338
INFO "GET /containers/17/ HTTP/1.1" 200 28460
INFO Watching for file changes with StatReloader
INFO "GET / HTTP/1.1" 302 0
INFO "GET /login/?next=/ HTTP/1.1" 200 15024
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 304 0
INFO "POST /login/?next=/ HTTP/1.1" 302 0
INFO "GET / HTTP/1.1" 200 43849
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 200 364003
ERROR Internal Server Error: /statistiques/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/v3/manifest_app/views.py", line 212, in statistiques
    return render(request, 'manifest_app/statistiques.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1379, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'voyage'. Choices are: pdf_document, vessel, container, shipper, consigne
ERROR "GET /statistiques/ HTTP/1.1" 500 218815
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 9391
ERROR Internal Server Error: /statistiques/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/v3/manifest_app/views.py", line 212, in statistiques
    return render(request, 'manifest_app/statistiques.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1379, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'voyage'. Choices are: pdf_document, vessel, container, shipper, consigne
ERROR "GET /statistiques/ HTTP/1.1" 500 218815
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /statistiques/ HTTP/1.1" 200 28012
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/tasks.py changed, reloading.
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/tasks.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO "GET / HTTP/1.1" 200 43849
INFO "GET /documents/ HTTP/1.1" 200 42237
INFO "GET /documents/upload/ HTTP/1.1" 200 17805
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 42864
INFO "POST /documents/16/process/ HTTP/1.1" 200 139
INFO "GET /documents/ HTTP/1.1" 200 41917
ERROR Internal Server Error: /documents/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/v3/manifest_app/views.py", line 236, in documents
    return render(request, 'manifest_app/documents.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 563, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 245: 'else', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR "GET /documents/ HTTP/1.1" 500 267960
ERROR Internal Server Error: /documents/
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/v3/manifest_app/views.py", line 236, in documents
    return render(request, 'manifest_app/documents.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/template/base.py", line 563, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 245: 'else', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR "GET /documents/ HTTP/1.1" 500 267960
INFO "GET /documents/ HTTP/1.1" 200 42260
INFO "POST /documents/16/process/ HTTP/1.1" 200 139
INFO "GET /documents/ HTTP/1.1" 200 42269
INFO "GET /documents/ HTTP/1.1" 200 42260
INFO "GET /documents/16/results/ HTTP/1.1" 200 525960
INFO /home/akemi/Bureau/Gnosis/v3/manifest_project/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_project/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_project/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_project/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_project/celery.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET /admin/ HTTP/1.1" 200 14133
INFO "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 18933
INFO "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO "POST /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 69215
INFO "GET /static/admin/js/cancel.js HTTP/1.1" 304 0
INFO "POST /admin/manifest_app/pdfdocument/ HTTP/1.1" 302 0
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 11845
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
WARNING Not Found: /documents/16/results/
WARNING "GET /documents/16/results/ HTTP/1.1" 404 4851
INFO "GET /documents/ HTTP/1.1" 200 17397
INFO "GET /documents/upload/ HTTP/1.1" 200 17805
INFO "POST /documents/upload/ HTTP/1.1" 302 0
INFO "GET /documents/ HTTP/1.1" 200 20348
INFO "POST /documents/17/process/ HTTP/1.1" 200 139
INFO "GET /documents/ HTTP/1.1" 200 19405
INFO Watching for file changes with StatReloader
INFO "GET /admin/ HTTP/1.1" 200 14663
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 9391
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 13433
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/pdfdocument/17/change/ HTTP/1.1" 200 17524
INFO "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO "POST /admin/manifest_app/pdfdocument/17/change/ HTTP/1.1" 302 0
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 13664
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET / HTTP/1.1" 200 33550
INFO "GET /documents/ HTTP/1.1" 200 19396
INFO "POST /documents/17/process/ HTTP/1.1" 200 139
INFO "GET /documents/ HTTP/1.1" 200 19405
INFO "GET /documents/ HTTP/1.1" 200 19405
INFO "GET /documents/ HTTP/1.1" 200 19405
INFO "GET /media/images/logo-gnosis.png HTTP/1.1" 200 364003
INFO "GET /media/images/logo-gnosis-2.png HTTP/1.1" 200 67739
INFO "GET / HTTP/1.1" 200 33564
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO "GET /containers/ HTTP/1.1" 200 22817
INFO "GET /documents/ HTTP/1.1" 200 19405
INFO "GET /admin/ HTTP/1.1" 200 14721
WARNING Not Found: /favicon.ico
WARNING "GET /favicon.ico HTTP/1.1" 404 9391
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 13433
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/pdfdocument/17/change/ HTTP/1.1" 200 17524
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "POST /admin/manifest_app/pdfdocument/17/change/ HTTP/1.1" 302 0
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 13664
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /documents/ HTTP/1.1" 200 19396
INFO "POST /documents/17/process/ HTTP/1.1" 200 139
INFO "GET /documents/ HTTP/1.1" 200 19405
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 13433
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/shipper/ HTTP/1.1" 200 20530
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/manifestentry/ HTTP/1.1" 200 60946
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO "GET /admin/manifest_app/container/ HTTP/1.1" 200 49024
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /documents/ HTTP/1.1" 200 19732
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 13433
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/pdfdocument/17/change/ HTTP/1.1" 200 123120
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /documents/ HTTP/1.1" 200 19732
INFO "GET /admin/manifest_app/manifestentry/ HTTP/1.1" 200 60946
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 13433
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /admin/manifest_app/pdfdocument/17/change/ HTTP/1.1" 200 123120
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "POST /admin/manifest_app/pdfdocument/17/change/ HTTP/1.1" 302 0
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 13664
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
INFO "GET /documents/ HTTP/1.1" 200 19739
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/tasks.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/akemi/Bureau/Gnosis/v3/manifest_app/tasks.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 302 0
INFO "GET /admin/login/?next=/admin/manifest_app/pdfdocument/ HTTP/1.1" 200 4285
INFO "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO "GET /documents/ HTTP/1.1" 302 0
INFO "GET /login/?next=/documents/ HTTP/1.1" 200 15024
INFO "POST /admin/login/?next=/admin/manifest_app/pdfdocument/ HTTP/1.1" 302 0
WARNING Forbidden (CSRF token from POST incorrect.): /login/
WARNING "POST /login/?next=/documents/ HTTP/1.1" 403 2526
INFO "GET /admin/manifest_app/pdfdocument/ HTTP/1.1" 200 11694
INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8985
WARNING Forbidden (CSRF token from POST incorrect.): /login/
WARNING "POST /login/?next=/documents/ HTTP/1.1" 403 2526
INFO "GET /login/ HTTP/1.1" 200 12846
ERROR Internal Server Error: /
Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedFunction: function strftime(unknown, date) does not exist
LINE 1: SELECT (strftime('%Y-%m', date)) AS "month", COUNT("manifest...
                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/Bureau/Gnosis/v3/manifest_app/views.py", line 180, in home
    'monthly_entries': list(monthly_entries),
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/query.py", line 210, in __iter__
    for row in compiler.results_iter(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1525, in results_iter
    results = self.execute_sql(
              ^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/akemi/anaconda3/envs/django/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: function strftime(unknown, date) does not exist
LINE 1: SELECT (strftime('%Y-%m', date)) AS "month", COUNT("manifest...
                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

ERROR "GET / HTTP/1.1" 500 140376
INFO /home/akemi/Bureau/Gnosis/v3/manifest_project/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
